import { Providers } from '@/store/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ToastProvider from '@/common/ToastProvider';
import 'react-toastify/dist/ReactToastify.css';
import 'reactjs-popup/dist/index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <ToastProvider>{children}</ToastProvider>
        </Providers>
        <div id='modals' />
      </body>
    </html>
  );
}
